---
site_name: "sepio-linkml"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - mermaid2:
      version: 10.9.0
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
  - Core IM Diagram: core-im-diagram.md
site_url: https://sepio-framework.github.io/sepio-linkml
repo_url: https://github.com/sepio-framework/sepio-linkml

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
